package com.igp.reviewservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;
import org.joda.time.DateTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "review-table")
public class Review {

    @DynamoDBHashKey(attributeName = "reviewId")
    @DynamoDBAutoGeneratedKey
    private String reviewId;

    @DynamoDBAttribute(attributeName = "eventId")
    private String eventId;

    @DynamoDBAttribute(attributeName = "rating")
    private int rating;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "creationDate")
    private DateTime creationDate;

    @DynamoDBAttribute(attributeName = "lastModificationDate")
    private DateTime lastModificationDate;

}
